repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --directory session-02-dockerization-and-code-quality mypy app
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --directory session-02-dockerization-and-code-quality pytest
        language: system
        pass_filenames: false