"""add composite index on task status priority id

Revision ID: f7715786b494
Revises: aae8fcd27de6
Create Date: 2026-09-12 11:43:42.784728

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f7715786b494"
down_revision: str | None = "aae8fcd27de6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_task_status_priority_id",
        "task",
        ["status", "priority", sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_status_priority_id", table_name="task")
    # ### end Alembic commands ###
